### ISSUE TITLE
Dashboard doesn't seem to connect to api

### ISSUE THREAD

**Issue by rbarcante** [brunabxs/gitlab-dashboard#1]
Hi,

I'm interested in using your add-on on firefox but it seems to don't connect at all to gitlab.com
with my api token.

**Api url**: https://gitlab.com
**Browser**: Firefox version 56.0
**OS**: Fedora 26 64-bits

Is the api correct?

Thanks.

**Comment by brunabxs** [comment]
Hi Ricardo,

Your api URL should be:

https://gitlab.com/api/v4

Let me know if you have any issues!

Regards,
Bruna

Em ter, 7 de nov de 2017 14:55, Ricardo Barçante <notifications@github.com>
escreveu:

**Comment by rbarcante** [comment]
Thank you very much, it worked 👍
